### ISSUE TITLE
Viral Heat is working and future of the package

### ISSUE THREAD

**Issue by diegocgaona** [mananshah99/sentR#2]
Hi @mananshah99 ,

Thanks for the great job!

I have some doubts before use the package. The Viral Heat still working? I saw that they were buyed by other company.
And you will implement other methods in the future or will work only with Naive Bayes.

Thanks!!!

**Comment by mananshah99** [comment]
@diegocgaona, the viralheat api access point should still be functioning, regardless of their acquisition by Cision Social Suite (see https://www.viralheat.com/developer/documentation/sentiment-api/). However, if you do experience issues, feel free to message me and I'll try to fix the GET url.

I'm hoping to implement other methods in the future, but currently aggregate and naive bayes are available.
